
---
title: "blog"
date: 2021-05-23
---

theme: minima
title: Cyber Blog
author: tttdrop
email: b.cariahall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A digital notepad essentially. To mark my progress.
# social links
twitter_username: will update # DO NOT include the @ character, or else the build will fail!
github_username:  tttdrop # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
